"""
Minimal OpenRouter client wrapper used for optional AI commentary.

This module intentionally keeps the integration lightweight and can be
mocked in tests to avoid real network calls.
"""

import os
from typing import Optional

from backend.models.recommendation_model import (
    RecommendationRequest,
    RecommendationResult,
)

OPENROUTER_API_KEY_ENV = "OPENROUTER_API_KEY"


def _build_prompt(result: RecommendationResult, request: RecommendationRequest) -> str:
    base = (
        f"Severity: {result.severity}. "
        f"Justification: {result.justification}. "
        f"Recommendations: {[rec.title for rec in result.recommendations]}."
    )
    if request.context and request.context.scenario_name:
        base = f"Scenario {request.context.scenario_name}. " + base
    return base


def get_explanation(
    *,
    result: RecommendationResult,
    request: RecommendationRequest,
) -> str:
    """
    Build a short explanation string. Replace with a real OpenRouter call when available.
    """
    api_key: Optional[str] = os.getenv(OPENROUTER_API_KEY_ENV)
    if not api_key:
        raise RuntimeError("OpenRouter API key is not configured.")

    prompt = _build_prompt(result, request)
    return (
        "AI commentary (simulated): "
        f"{prompt} This text would be generated by the configured language model."
    )
