export const UI_TEXTS_ES = {
    app: {
        title: "Simulador Urbano – Tablero Fase 2",
        intro: "Sigue los pasos en orden para configurar parámetros, ejecutar el escenario A, explorar las capas del mapa, comparar A/B y solicitar recomendaciones.",
    },
    sections: {
        sectionLabel: "Sección",
        simulationParams: {
            title: "Parámetros de simulación",
            subtitle: "Configura las entradas del escenario A antes de enviarlas al endpoint /api/v1/simulate.",
        },
        runSimulation: {
            title: "Ejecutar simulación (A)",
            subtitle: "Envía los parámetros configurados al backend y espera los KPI más recientes.",
            tip: "Consejo: mantén horizontes entre 12 y 72 pasos para ejecuciones ágiles. El nivel de tráfico y las restricciones se validan antes de enviar.",
        },
        mapVisualization: {
            title: "Visualización del mapa",
            subtitle: "Explora el mapa del Valle de Aburrá. Capas: sectores, puntos de monitoreo y mapa de calor.",
            empty: "Ejecuta una simulación para ver los sectores, puntos y el mapa de calor.",
        },
        kpis: {
            title: "KPIs",
            subtitle: "Indicadores por sector con base en el último paso del tiempo simulado.",
            noResults: "Aún no hay resultados. Ejecuta la simulación para ver los KPI de cada sector.",
            missingZonesTitle: "Faltan zonas",
            missingZonesMessage: "El backend no devolvió zonas para esta ejecución.",
            scenarioLabel: "Escenario",
            horizonLabel: "Horizonte",
            horizonSteps: "pasos",
            trafficLabel: "Nivel de tráfico",
            pollutionLatest: "PM2.5 (último paso):",
            trafficRelative: "Tráfico (rel.):",
            notAvailable: "n/d",
        },
        comparison: {
            title: "Comparación A/B",
            subtitle: "Construye dos escenarios y compáralos visualmente (lado a lado o control deslizante).",
            instructions: "Llena las tarjetas A y B con tráfico y políticas, luego ejecuta la solicitud de comparación.",
            sideBySide: "Lado a lado",
            overlay: "Superpuesto (slider)",
            successTitle: "Comparación lista",
            errorTitle: "Error al comparar",
            successMessage: (labelA: string, labelB: string, steps: number | string) => `A = ${labelA} • B = ${labelB} (pasos ${steps})`,
            mapNotReady: "Configura los escenarios A y B y ejecuta una comparación para ver los mapas.",
            loadingBase: "Cargando zonas base para la comparación...",
        },
        recommendations: {
            title: "Recomendaciones",
            subtitle: "Solicita acciones de mitigación basadas en reglas, con comentario opcional de IA.",
            locked: "Ejecuta primero la simulación para obtener KPI y habilitar este botón.",
        },
    },
    form: {
        legendLabel: "Etiqueta para la leyenda",
        legendHint: "Se mostrará en la leyenda de comparación.",
        legendTooltip: "Nombra cada escenario para que la leyenda de comparación sea clara.",
        legendPlaceholder: "Línea base / Mitigación",
        scenario: "Escenario",
        scenarioTooltip: "Escenario A (línea base) vs Escenario B (intervención).",
        trafficLevel: "Nivel de tráfico",
        trafficTooltip: "Un nivel más alto aumenta la congestión base.",
        horizon: "Horizonte",
        horizonHint: "Pasos de tiempo (>= 1)",
        horizonTooltip: "Mínimo 1. Valores altos aumentan el tiempo de ejecución.",
        picoYPlaca: "Pico y placa activado",
        picoYPlacaTooltip: "Activa la restricción en horas pico para vehículos particulares.",
        cargoRestriction: "Restricción de carga pesada",
        cargoRestrictionTooltip: "Restringe la circulación de carga pesada durante el horizonte.",
        advancedNote: "Los interruptores avanzados son opcionales y solo afectan la carga útil de la comparación A/B.",
    },
    toggles: {
        useAi: "Usar comentario de IA",
        useAiTooltip: "Agrega contexto generado por IA a las acciones recomendadas.",
        autoRecommend: "Auto-generar recomendaciones",
        autoRecommendTooltip: "Solicita recomendaciones automáticamente después de cada ejecución exitosa.",
    },
    buttons: {
        runSimulation: "Ejecutar simulación",
        runningSimulation: "Ejecutando simulación...",
        compareScenarios: "Comparar escenarios",
        comparing: "Comparando...",
        getRecommendations: "Obtener recomendaciones",
        loadingRecommendations: "Cargando...",
    },
    options: {
        traffic: {
            low: "Bajo",
            medium: "Medio",
            high: "Alto",
        },
        scenarios: {
            a: "A",
            b: "B",
            labelA: "Escenario A",
            labelB: "Escenario B",
            defaultLabelA: "Escenario A (línea base)",
            defaultLabelB: "Escenario B (política)",
        },
    },
    messages: {
        horizonInvalid: "Ingresa un horizonte de al menos 1 paso de tiempo para ejecutar la simulación.",
        simulationFailed: "La simulación falló. Intenta nuevamente.",
        comparisonFailed: "La comparación falló. Intenta nuevamente.",
        runFirstForRecommendation: "Ejecuta primero una simulación para generar recomendaciones.",
        incompleteForRecommendation: "Los datos de la simulación están incompletos para las recomendaciones.",
        noResultsYet: "Aún no hay resultados. Configura los parámetros y haz clic en Ejecutar simulación.",
        waitingBackend: "Esperando respuesta del backend... esto puede tardar unos segundos según el horizonte.",
        latestRunTitle: "Última ejecución",
        mapUnavailablePrefix: "Mapa avanzado no disponible: ",
        comparisonMapUnavailablePrefix: "Mapa de comparación no disponible: ",
        zonesPrompt: "Ejecuta una simulación para mostrar las capas avanzadas.",
        loadingZones: "Cargando zonas para el mapa...",
        failedLoadZones: (status: number | string) => `No se pudieron cargar las zonas (estado ${status}).`,
        validationOrApi: "Validación o problema de API",
    },
    legend: {
        ariaLabel: "Leyenda de calidad del aire",
        title: "Escala de calidad del aire",
        subtitle: "Paleta compartida para zonas, puntos de monitoreo y mapa de calor.",
        layersTitle: "Capas",
        layersDescription: "Activa las capas para enfocarte en los datos que necesitas.",
        zones: "Zonas (sectores)",
        zonesTooltip: "Polígonos coloreados con las métricas más recientes de contaminación y tráfico por sector.",
        points: "Puntos (sensores)",
        pointsTooltip: "Puntos y sensores; el tamaño sigue el PM2.5 en el último paso de tiempo.",
        heatmap: "Mapa de calor",
        heatmapTooltip: "Mapa de calor para encontrar áreas críticas en el valle.",
    },
    map: {
        heatmap: "Mapa de calor",
        zones: "Zonas",
        points: "Puntos",
        scenarioA: "Escenario A",
        scenarioB: "Escenario B",
        legend: "Leyenda",
        statusNeedsSimulation: "Ejecuta una simulación para mostrar las capas avanzadas.",
        statusLoading: "Cargando zonas para el mapa...",
        zoneFallback: "Zona",
        pointFallback: "Punto de zona",
    },
    recommendations: {
        heading: "Recomendaciones",
        subtitle: "Mayores niveles de PM2.5 y congestión generan acciones más estrictas.",
        aiCommentary: "Comentario de IA",
        justification: "Justificación",
        kpiSummary: "Resumen de KPI",
        codeLabel: "Código",
        statuses: {
            loading: "Generando recomendaciones...",
            idle: "Ejecuta una simulación y solicita recomendaciones para ver resultados aquí.",
            empty: "No se requieren medidas restrictivas según los KPI actuales.",
            errorGeneric: "No se pudieron obtener las recomendaciones. Intenta de nuevo.",
            error401: "Acceso denegado (401): verifica tu clave API antes de solicitar recomendaciones.",
        },
        listEmpty: "No hay acciones recomendadas para este escenario.",
        severityNote: "Mayor severidad implica acciones más estrictas.",
        kpiSummaryUnavailable: "Resumen de KPI no disponible.",
    },
    severity: {
        low: "Bajo",
        moderate: "Moderado",
        high: "Alto",
        critical: "Crítico",
    },
    bucketLabels: {
        low: "Bajo",
        moderate: "Moderado",
        high: "Alto",
        critical: "Crítico",
    },
    errors: {
        error401: "Clave de acceso inválida o ausente.",
        serverError: "Ocurrió un error en el servidor. Por favor intenta de nuevo.",
        invalidParameters: "Parámetros inválidos. Revisa los campos resaltados.",
        compareUnavailable: "Configura los escenarios A y B, luego ejecuta una comparación para ver los mapas.",
    },
    metrics: {
        pm: "PM2.5",
        traffic: "Tráfico",
        relative: "(rel.)",
        average: "(prom.)",
        lastStep: "(último paso)",
        timeIndex: "Índice de tiempo",
    },
    kpiLabels: {
        pm25_max: "PM2.5 máximo",
        pm25_avg: "PM2.5 promedio",
        congestion_index: "Índice de congestión",
    },
};
