from typing import Dict, List, Literal

from pydantic import BaseModel, Field


SeverityLevel = Literal["low", "moderate", "high", "critical"]


class RecommendationItem(BaseModel):
    """Single recommended action generated by the rules engine."""

    code: str = Field(..., description="Stable identifier for the recommendation.")
    title: str = Field(..., description="Short human-readable title.")
    description: str = Field(..., description="Detailed explanation of the action.")


class RecommendationResult(BaseModel):
    """Structured output of the rule-based policy recommendation engine."""

    severity: SeverityLevel = Field(
        ...,
        description="Overall severity level considering pollution, congestion and environment.",
    )
    recommendations: List[RecommendationItem] = Field(
        default_factory=list,
        description="Ordered list of policy recommendations to apply.",
    )
    justification: str = Field(
        ...,
        description="Human-readable explanation summarizing the drivers behind the decision.",
    )
    kpi_summary: Dict[str, float] = Field(
        default_factory=dict,
        description="Compact numeric snapshot of key KPIs (e.g. avg/max PM2.5, congestion).",
    )
