import time
from typing import Dict

from fastapi import APIRouter, Body, Depends, Request

from backend.core.logging_config import get_logger, log_error, log_request, log_result
from backend.core.security import API_KEY_HEADER_NAME, get_api_key

from backend.models.recommendation_model import RecommendationRequest, RecommendationResponse
from backend.services.recommendation_service import build_recommendation_response

logger = get_logger(__name__)

router = APIRouter(
    prefix="/recommend",
    tags=["Recommendations"],
    dependencies=[Depends(get_api_key)],
)

RECOMMEND_REQUEST_EXAMPLES = {
    "criticalCase": {
        "summary": "High PM2.5 and congestion",
        "description": "Critical pollution and congestion overlapping in Bello triggers strict measures.",
        "value": {
            "kpis": {
                "pm25_max": 72.5,
                "pm25_avg": 58.2,
                "congestion_index": 0.85,
                "zones": [
                    {"name": "Bello", "pm25": 72.5, "congestion": 0.88},
                    {"name": "Medellin", "pm25": 49.0, "congestion": 0.62},
                ],
            },
            "context": {"scenario_name": "B", "wind_speed": 1.5, "wind_direction": 230.0},
        },
    },
    "moderateCase": {
        "summary": "Moderate pollution and congestion",
        "description": "Balanced KPIs lead to informative, non-restrictive guidance.",
        "value": {
            "kpis": {
                "pm25_max": 34.2,
                "pm25_avg": 26.0,
                "congestion_index": 0.42,
                "zones": [
                    {"name": "Envigado", "pm25": 34.2, "congestion": 0.45},
                    {"name": "Itagui", "pm25": 27.0, "congestion": 0.38},
                ],
            },
            "context": {"scenario_name": "A", "wind_speed": 3.4},
        },
    },
    "withLlm": {
        "summary": "Request AI commentary",
        "description": "Same KPIs as criticalCase but asks for optional LLM explanation.",
        "value": {
            "kpis": {
                "pm25_max": 72.5,
                "pm25_avg": 58.2,
                "congestion_index": 0.85,
                "zones": [
                    {"name": "Bello", "pm25": 72.5, "congestion": 0.88},
                    {"name": "Medellin", "pm25": 49.0, "congestion": 0.62},
                ],
            },
            "context": {"scenario_name": "B"},
            "use_llm": True,
        },
    },
}

RECOMMEND_RESPONSE_EXAMPLE = {
    "severity": "critical",
    "recommendations": [
        {"code": "ENV_ALERT", "title": "Activate environmental alert", "description": "PM2.5 exceeds 55 ug/m3; activate emergency protocols city-wide."},
        {"code": "FREIGHT_RESTRICTION", "title": "Restrict freight vehicles", "description": "Limit heavy freight activity in critical corridors to reduce emissions quickly."},
    ],
    "justification": "Max PM2.5: 72.5 ug/m3; Max congestion index: 0.88; Severe congestion in: Bello; High pollution and congestion overlap in: Bello",
    "kpi_summary": {
        "pm25_avg": 58.2,
        "pm25_max": 72.5,
        "max_congestion": 0.88,
        "zones_high_pm25": 1.0,
        "zones_high_congestion": 1.0,
    },
    "llm_commentary": (
        "AI commentary (simulated): Severity: critical. Justification: Max PM2.5: 72.5 ug/m3; "
        "Max congestion index: 0.88; Severe congestion in: Bello; High pollution and congestion overlap in: Bello. "
        "Recommendations: ['Activate environmental alert', 'Restrict freight vehicles']. "
        "This text would be generated by the configured language model."
    ),
}


@router.post(
    "",
    response_model=RecommendationResponse,
    summary="Get rule-based policy recommendations",
    description=(
        "Transforms KPI snapshots from simulations into policy recommendations using the rule engine. "
        "If configured, the response can include an optional AI commentary to help explain the rationale."
    ),
    responses={
        200: {
            "description": "Recommendations generated successfully.",
            "content": {"application/json": {"example": RECOMMEND_RESPONSE_EXAMPLE}},
        },
        422: {
            "description": "Validation error in request payload.",
        },
    },
)
async def recommend_policies(
    payload: RecommendationRequest = Body(..., examples=RECOMMEND_REQUEST_EXAMPLES),
    fastapi_request: Request,
) -> RecommendationResponse:
    start = time.perf_counter()
    endpoint_name = "/api/v1/recommend"
    params_dict = payload.model_dump(exclude_none=True)
    api_key = fastapi_request.headers.get(API_KEY_HEADER_NAME)
    log_request(logger, endpoint_name, params_dict, api_key)

    try:
        response = build_recommendation_response(payload)
    except Exception as exc:
        log_error(logger, endpoint_name, exc)
        raise

    execution_ms = int((time.perf_counter() - start) * 1000)
    summary: Dict[str, int | str | Dict[str, float]] = {
        "severity": response.severity,
        "recommendations_count": len(response.recommendations),
    }
    if response.kpi_summary:
        summary["kpi_summary"] = response.kpi_summary
    log_result(logger, endpoint_name, execution_ms, summary)
    return response
